trigger:
  batch: false
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md

pr: none
# pr:
#   autoCancel: true
#   branches:
#     include:
#       - master
#   paths:
#     exclude:
#       - README.md
#       - .azure/pipelines/nightly.yml
#       - .azure/pipelines/pkg.yml
#       - .azure/pipelines/cd.json

schedules:
  - cron: "0 0 * * *"
    displayName: "Daily midnight build"
    branches:
      include:
        - main
    always: true

variables:
  # library variable groups
  - group: "build-tools"
  - group: "devproapp-testing"
  # common task variables
  - name: "dotnet.sdk.version"
    value: "10.0.x"
  - name: "BuildConfiguration"
    value: "Debug"
  - name: "SolutionFile"
    value: "KeepTrack.slnx"
  - name: "TestProjects"
    value: "test/*Tests/*.csproj"
  - name: "UnitTestProjects"
    value: "test/*UnitTests/*.csproj"
  - name: "IntegrationTestProjects"
    value: "test/*IntegrationTests/*.csproj"

stages:
  # Unit testing
  - stage: "unit_testing"
    displayName: "Unit testing"
    jobs:
      - job: "linux_unittests"
        displayName: "Unit tests run on Linux"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: UseDotNet@2
            displayName: "Use .NET Core SDK"
            inputs:
              packageType: "sdk"
              version: $(dotnet.sdk.version)
          - task: DotNetCoreCLI@2
            displayName: "Build .NET solution"
            inputs:
              command: "build"
              projects: "$(SolutionFile)"
              arguments: "-c $(BuildConfiguration)"
            env:
              DOTNET_CLI_TELEMETRY_OPTOUT: 1
              DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
              COREHOST_TRACE: 0
          - task: DotNetCoreCLI@2
            displayName: "Run .NET unit tests"
            inputs:
              command: "test"
              projects: "$(UnitTestProjects)"
              arguments: "--configuration $(BuildConfiguration)"
            env:
              DOTNET_CLI_TELEMETRY_OPTOUT: 1
              DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
              COREHOST_TRACE: 0

  # Integration testing
  - stage: "integration_testing"
    displayName: "Integration testing"
    dependsOn: []
    condition: eq(variables['RunIntegrationTestingStage'], true)
    jobs:
      - job: "windows_integrationtests"
        displayName: "Windows CI"
        pool:
          # code coverage generation only works on Windows for the moment
          vmImage: "windows-latest"
        steps:
          - task: UseDotNet@2
            displayName: "Use .NET Core SDK"
            inputs:
              packageType: "sdk"
              version: $(dotnet.sdk.version)
          - task: PowerShell@2
            displayName: "Start local MongoDB"
            inputs:
              targetType: "inline"
              script: |
                Write-Host "Starting MongoDB"
                md log
                md data
                Start-Process -FilePath "mongod" -ArgumentList "--logpath log/mongod.log", "--dbpath data", "--port 27017" -WindowStyle Hidden
          - task: DotNetCoreCLI@2
            displayName: "Restore .NET packages"
            inputs:
              command: "restore"
              projects: "$(SolutionFile)"
              feedsToUse: "select"
              noCache: $(dotnet.cache.disable)
            env:
              DOTNET_CLI_TELEMETRY_OPTOUT: 1
              DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
              COREHOST_TRACE: 0
          - task: DotNetCoreCLI@2
            displayName: "Build .NET solution"
            inputs:
              command: "build"
              projects: "$(SolutionFile)"
              arguments: "-c $(BuildConfiguration)"
            env:
              DOTNET_CLI_TELEMETRY_OPTOUT: 1
              DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
              COREHOST_TRACE: 0
          - task: DotNetCoreCLI@2
            displayName: "Run .NET test projects"
            inputs:
              command: "test"
              projects: "$(TestProjects)"
              arguments: '--configuration $(BuildConfiguration) --filter "Environment=Localhost|Category=UnitTests" --collect "Code coverage"'
            env:
              DOTNET_CLI_TELEMETRY_OPTOUT: 1
              DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
              COREHOST_TRACE: 0
              AllowedOrigins__0: http://localhost:4200
              Infrastructure__MongoDB__ConnectionString: mongodb://localhost:27017
              Infrastructure__MongoDB__DatabaseName: keeptrack_integrationtests
              Authentication__JtBearer__TokenValidation__Issuer: $(keeptrack.jwtbearer.tokenvalidation.issuer)
              Authentication__JwtBearer__Authority: $(keeptrack.jwtbearer.authority)
              Authentication__JwtBearer__TokenValidation__Audience: $(keeptrack.jwtbearer.tokenvalidation.audience)
              Firebase__Application__Key: $(firebase.apikey)
              Firebase__Username: $(firebase.testing.user0.username)
              Firebase__Password: $(firebase.testing.user0.password)
          - task: PublishBuildArtifacts@1
            displayName: "Publish artifacts"
            condition: failed()
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "drop"
              publishLocation: "Container"
