stages:
  - build
  # - test # TODO
  # - package # TODO

workflow:
  rules:
    # - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "web"

variables:
  DOTNET_VERSION: "10.0"

build:
  image: mcr.microsoft.com/dotnet/sdk:$DOTNET_VERSION
  stage: build
  script:
    - dotnet restore
    - dotnet build --no-restore --configuration Debug
