using Keeptrack.Domain.Models;
using Riok.Mapperly.Abstractions;

namespace Keeptrack.WebApi.Mappers;

[Mapper(EnumMappingStrategy = EnumMappingStrategy.ByName)]
[UseStaticMapper(typeof(CommonDtoMappings))]
public partial class HouseDtoMapper : IDtoMapper<HouseDto, HouseModel>
{
    // see BookDtoMapper.ToModel for why MapValue (not MapperIgnoreTarget) is required here
    [MapValue(nameof(HouseModel.OwnerId), "")]
    public partial HouseModel ToModel(HouseDto dto);

    [MapperIgnoreSource(nameof(HouseModel.OwnerId))]
    public partial HouseDto ToDto(HouseModel model);

    /// <summary>
    /// HouseDto.PropertyType is nullable (PropertyType?) while HouseModel.PropertyType is required - the
    /// same "nullable DTO member mapping to a required model member" gotcha as CarDtoMapper.EnergyType,
    /// so it needs the same hand-written null -> default fallback wrapping the generated ByName conversion.
    /// </summary>
    [UserMapping]
    private Domain.Models.PropertyType ToRequiredPropertyType(Contracts.Dto.PropertyType? value)
    {
        return value.HasValue ? MapPropertyType(value.Value) : default;
    }

    private partial Domain.Models.PropertyType MapPropertyType(Contracts.Dto.PropertyType value);
}
